"""create diagnostic session tables

Revision ID: 5cb2f61def70
Revises: 0006
Create Date: 2026-08-21 16:14:03.736764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', postgresql.ENUM('BIKE', 'CAR', name='vehicletype', create_type=False), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='diagnosticstatus'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_mechanic', sa.Boolean(), nullable=True),
    sa.Column('possible_causes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('follow_up_questions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_sessions_customer_id'), 'diagnostic_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_status'), 'diagnostic_sessions', ['status'], unique=False)
    op.create_table('diagnostic_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_messages_session_id'), 'diagnostic_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_messages_session_id'), table_name='diagnostic_messages')
    op.drop_table('diagnostic_messages')
    op.drop_index(op.f('ix_diagnostic_sessions_status'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_customer_id'), table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    # ### end Alembic commands ###
